title: LVL References
description: Reference material for LVL Motion sensors and apps
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      layout: default
